### ISSUE TITLE
有关可选购的飞控和机载电脑

### ISSUE THREAD

**Issue by J1dan** [ZJU-FAST-Lab/Fast-Drone-250#3]
你们好，请问可选购的三种飞控有什么使用上的区别吗？是否有更推荐的一种？
另一个问题是关于Xavier NX，官方套件就是核心板+底板，那么还需要再购买表中的NX载板吗？是否有什么不同？
谢谢！

**Comment by PanNeng-ZJU** [comment]
@J1dan 
1.个人更推荐CUAV NORA，因为体积相较其他两款更小一些，性能上都比较相似。
2.表中的载板体积更小，更适合使用在无人机上，但相应的USB接口也更少，如果您对机载电脑体积没有要求，可以不购买额外的载板。另外官方的底板不太好固定在飞机上，可能需要用比较厚的海绵胶粘起来

**Comment by J1dan** [comment]
非常感谢您！

**Comment by J1dan** [comment]
您好，再请问一下如果是购买NX载板的话，是不是就只需要购买NX核心板然后装上去就可以了？也就是说不需要购买NX开发板？我看价目表里的Xavier NX价格是6800，但核心板的价格只要3699，所以有点好奇如果另买载板的话是否还是需要购买开发者套件。

**Comment by PanNeng-ZJU** [comment]
我的建议是不缺预算的话购买开发者套件。因为单独购买的核心板是不能插SD卡的，装系统的SD卡必须插在NX载板上，而这需要另打驱动，比较麻烦。开发者套件里的核心板是支持SD卡的，可以即插即用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJU-FAST-Lab/Fast-Drone-250"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:02
***@***.***&gt;;
抄送:&nbsp;"自动化（交叉）1701 ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ZJU-FAST-Lab/Fast-Drone-250] 有关可选购的飞控和机载电脑 (Issue #3)





 
您好，再请问一下如果是购买NX载板的话，是不是就只需要购买NX核心板然后装上去就可以了？也就是说不需要购买NX开发板？我看价目表里的Xavier NX价格是6800，但核心板的价格只要3699，所以有点好奇如果另买载板的话是否还是需要购买开发者套件。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by J1dan** [comment]
谢谢解答，但是我还是有点迷惑：之前您说表中的载板体积更小，我理解为更推荐使用表中的载板；但是如果购买开发板的话，不是就不需要另外的载板了吗？
或者换句话说，我现在不缺预算，那么是不是更推荐购买开发者套件加上表中889的载板？还是只需要开发者套件，或官方核心板+889载板？麻烦您建议一下。麻烦您了！

**Comment by PanNeng-ZJU** [comment]
购买开发者套件+889的载板，把开发者套件里的核心板拆出来装在889的载板上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJU-FAST-Lab/Fast-Drone-250"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 中午12:22
***@***.***&gt;;
抄送:&nbsp;"自动化（交叉）1701 ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ZJU-FAST-Lab/Fast-Drone-250] 有关可选购的飞控和机载电脑 (Issue #3)





 
谢谢解答，但是我还是有点迷惑：之前您说表中的载板体积更小，我理解为更推荐使用表中的载板；但是如果购买开发板的话，不是就不需要另外的载板了吗？
 或者换句话说，我现在不缺预算，那么是不是更推荐购买开发者套件加上表中889的载板？还是只需要开发者套件，或官方核心板+889载板？麻烦您建议一下。麻烦您了！
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by J1dan** [comment]
谢谢，刚才去问了一下开发板的卖家，但他们说开发板的SD卡也是插在底板上的，所以单卖的核心板和开发板上的核心板应该没有区别；而889载板的卖家说可以在他们家买核心板+他们的底板，可以帮忙装好ubuntu系统，随后我们再自己装SD卡，根据他们的教程设置从SD卡启动系统。请问您觉得这个方案怎么样？

**Comment by PanNeng-ZJU** [comment]
可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJU-FAST-Lab/Fast-Drone-250"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午2:37
***@***.***&gt;;
抄送:&nbsp;"自动化（交叉）1701 ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ZJU-FAST-Lab/Fast-Drone-250] 有关可选购的飞控和机载电脑 (Issue #3)





 
谢谢，刚才去问了一下开发板的卖家，但他们说开发板的SD卡也是插在底板上的，所以单卖的核心板和开发板上的核心板应该没有区别；而889载板的卖家说可以在他们家买核心板+他们的底板，可以帮忙装好ubuntu系统，随后我们再自己装SD卡，根据他们的教程设置从SD卡启动系统。请问您觉得这个方案怎么样？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
